jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
language: java
#needed as a work around for https://github.com/travis-ci/travis-ci/issues/5227 which is a buffer overflow in openjdk7 due to using IPV6 (due to docker)
before_install:
  - sudo hostname "$(hostname | cut -c1-63)"
script: "gradle clean build"
