---
version: "{build}"

install:
- cmd: choco install gradle

build_script:
- cmd: gradle check dependencycheck

notifications:
- provider: Email
  to:
  - jsca@loc.gov
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
