---
version: "{build}"

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
- cmd: choco install gradle
- cmd: git clone --depth 3 https://github.com/loc-rdc/bagit-conformance-suite.git

build_script:
- cmd: gradle check --no-daemon

shallow_clone: true

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

notifications:
- provider: Email
  to:
  - jsca@loc.gov
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
