---
version: "{build}"

install:
- cmd: choco install gradle
- cmd: git clone --depth 3 https://github.com/loc-rdc/bagit-conformance-suite.git

build_script:
- cmd: gradle check

shallow_clone: true

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%USERPROFILE%\.gradle\caches'

notifications:
- provider: Email
  to:
  - jsca@loc.gov
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
