---
version: "{build}"

install:
- cmd: choco install gradle

build_script:
- cmd: gradle check dependencycheck

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%USERPROFILE%\.gradle'

notifications:
- provider: Email
  to:
  - jsca@loc.gov
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
