version: 2
jobs:
  build:
    working_directory: ~/LibraryOfCongress/bagit-java
    docker:
      - image: circleci/openjdk:8-jdk
#    filters:
#      branches:
#        only: master
    steps:
      - checkout #checks out your code to your working directory
      - restore_cache:
          keys:
            - dependency-cache
      - run ./gradlew check
      # Save dependency cache
      - save_cache:
          key: dependency-cache
          paths:
            - ~/.gradle
