name: Build documentation site

on:
  push:
    branches:
      - master

jobs:
  mkdocs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: adopt-openj9
          java-version: 17
          cache: 'maven'

      - name: Generate maven site
        run: mvn -B clean test site jacoco:report coveralls:report --file pom.xml -DrepoToken=${{ secrets.COVERALLS_REPO_TOKEN }} -Djarsigner.skip=true

      - name: Copy javadocs to site folder
        run: cp -r target/site/ docs/mvnsite/

      - name: Run script
        run: bash .github/workflows/mkdocs/mkdocs.sh
        shell: bash
